### ISSUE TITLE
Prepare for 1.0.0 release

### ISSUE THREAD

**Issue by Joonalai** [UnfoldedInc/qgis-plugin#8]
Plugin should have at least following:
- [x] Logo
- [x]  Tags including at least unfolded and kepler.gl'
- [x] Metadata description, about, author, email 
- [x] experimental status set to `false`
- [x] Final decision on the name of the plugin
- [x] Final decision on the package names
- [x] Documentation of the plugin
    - [x] Documentation in QGIS - presumably fairly short
    - [x] Documentation page in Unfolded Studio (markdown format) - Long page is good, should have screenshots and could even have an embedded example of a converted and published map, perhaps from some well-known QGIS example(s)
- [x] QGIS plugin repository upload (credentials as Github secrets)
- [x] Public repository
    - [x] Review/clean comment history to remove any internal discussions
- [x] Blog post
- [x] Links pointing to plugin documentation to the About panel
- [x] Something else?

**Comment by ibgreen** [comment]
> @ibgreen would you like to make the repository public and possibly clean the comment history?

Done
